apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jfbyg01cw-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jfbyg01cw-java-springboot-gitops